const data = {
  // users: [
  //   {
  //     firstName: 'ron',
  //     lastName: 'man',
  //     email: 'example@gmail.com',
  //     password: bcrypt.hashSync('123456'),
  //     country: 'Israel',
  //     city: 'Kochav',
  //     street: 'None',
  //     streetNumber: '5',
  //     aptNumber: '6',
  //     zip: '11111',
  //     isAdmin: true,
  //   },
  //   {
  //     firstName: 'nika',
  //     lastName: 'ta',
  //     email: 'example55@gmail.com',
  //     password: bcrypt.hashSync('123456'),
  //     country: 'Israel',
  //     city: 'Kochav',
  //     street: 'None',
  //     streetNumber: '5',
  //     aptNumber: '6',
  //     zip: '11111',
  //   },
  // ],
  products: [
    {
      title: 'Black Bag1',
      slug: 'Black-Bag1',
      image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80',
      brand: 'Nike',
      category: 'Backpack',
      color: 'Black',
      size:'M', 
      type: 'Men',
      description: 'high quality shirt',
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
    },
    {
      title: 'Black Bag2',
      slug: 'Black-Bag2',
      image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80',
      brand: 'Nike',
      category: 'Backpack',
      color: 'Black',
      size:'M', 
      type: 'Men',
      description: 'high quality shirt',
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
    },
    {
      title: 'Black Bag3',
      slug: 'Black-Bag3',
      image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80',
      brand: 'Nike',
      category: 'Backpack',
      color: 'Black',
      size:'M', 
      type: 'Men',
      description: 'high quality shirt',
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
    },
    {
      title: 'Black Bag5',
      slug: 'Black-Bag5',
      image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80',
      brand: 'Nike',
      category: 'Backpack',
      color: 'Black',
      size:'M', 
      type: 'Men',
      description: 'high quality shirt',
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
    },
    {
      title: 'Black Bag4',
      slug: 'Black-Bag4',
      image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80',
      brand: 'Nike',
      category: 'Backpack',
      color: 'Black',
      size:'M', 
      type: 'Men',
      description: 'high quality shirt',
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
    },
    {
      title: 'Black Bag6',
      slug: 'Black-Bag6',
      image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80',
      brand: 'Nike',
      category: 'Backpack',
      color: 'Black',
      size:'M', 
      type: 'Men',
      description: 'high quality shirt',
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
    },
    {
      title: 'Black Bag7',
      slug: 'Black-Bag7',
      image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80',
      brand: 'Nike',
      category: 'Backpack',
      color: 'Black',
      size:'M', 
      type: 'Men',
      description: 'high quality shirt',
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
    },
    {
      title: 'Black Bag8',
      slug: 'Black-Bag8',
      image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80',
      brand: 'Nike',
      category: 'Backpack',
      color: 'Black',
      size:'M', 
      type: 'Men',
      description: 'high quality shirt',
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
    },
    {
      title: 'Black Bag9',
      slug: 'Black-Bag9',
      image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80',
      brand: 'Nike',
      category: 'Backpack',
      color: 'Black',
      size:'M', 
      type: 'Men',
      description: 'high quality shirt',
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
    },
    {
      title: 'Black Bag10',
      slug: 'Black-Bag10',
      image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80',
      brand: 'Nike',
      category: 'Backpack',
      color: 'Black',
      size:'M', 
      type: 'Men',
      description: 'high quality shirt',
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
    },
    {
      title: 'Black Bag11',
      slug: 'Black-Bag11',
      image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80',
      brand: 'Nike',
      category: 'Backpack',
      color: 'Black',
      size:'M', 
      type: 'Men',
      description: 'high quality shirt',
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
    },
    {
      title: 'Black Bag12',
      slug: 'Black-Bag12',
      image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80',
      brand: 'Nike',
      category: 'Backpack',
      color: 'Black',
      size:'M', 
      type: 'Men',
      description: 'high quality shirt',
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
    },
    {
      title: 'Black Bag13',
      slug: 'Black-Bag13',
      image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80',
      brand: 'Nike',
      category: 'Backpack',
      color: 'Black',
      size:'M', 
      type: 'Men',
      description: 'high quality shirt',
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
    },
  ],
};
export default data;
